{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- if .Values.networkPolicy.ingress -}}
  {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
    - ports:
        - protocol: TCP
          port: {{ .Values.internalPort }}
        - protocol: TCP
          port: 9127
  {{- end -}}
  {{- if .Values.networkPolicy.egress -}}
  {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{ else }}
  egress:
    - {}
  {{ end }}
  {{ end }}
