apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-configfile
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  pgbouncer.ini: |-
{{ include "pgbouncer.ini.1.0.0" . | b64enc | indent 4 }}
